Repository openstack-k8s-operators/dataplane-operator, pull requests merged in 2023-07, with the labels that each got.

#260 Drop edpm_host_entries usage
  config/samples/dataplane_v1beta1_openstackdataplane.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_ceph.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_customnetworks.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_configure_network.yaml
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/01-assert.yaml
Labels: approved, lgtm

#261 Fix some issues that delay deployment
  config/services/dataplane_v1beta1_openstackdataplaneservice_configure_network.yaml
  pkg/deployment/baremetal.go
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/01-assert.yaml
Labels: approved, lgtm

#242 Use AEE instead of the Job to set status
  .pre-commit-config.yaml
  pkg/deployment/deployment.go
  pkg/util/ansible_execution.go
Labels: approved, lgtm

#262 Add defaulting and validation webhook
  Makefile
  PROJECT
  api/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  api/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  api/bases/dataplane.openstack.org_openstackdataplanes.yaml
  api/v1beta1/common.go
  api/v1beta1/conditions.go
  api/v1beta1/openstackdataplane_webhook.go
  api/v1beta1/openstackdataplanenode_types.go
  api/v1beta1/openstackdataplanerole_types.go
  api/v1beta1/openstackdataplaneservice_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplanes.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/openstackdataplane_controller.go
  controllers/openstackdataplanenode_controller.go
  controllers/openstackdataplanerole_controller.go
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  docs/openstack_dataplaneservice.md
  hack/clean_local_webhook.sh
  hack/configure_local_webhook.sh
  main.go
  pkg/deployment/baremetal.go
  pkg/deployment/ceph_client.go
  pkg/deployment/deployment.go
  pkg/deployment/inventory.go
  pkg/deployment/ipam.go
  pkg/deployment/nova.go
  pkg/deployment/nova_test.go
  pkg/deployment/service.go
  pkg/util/ansible_execution.go
  pkg/util/task.go
Labels: approved, lgtm

#266 Fixes on documentation
  .pre-commit-config.yaml
  Makefile
  README.md
  api/v1beta1/common.go
  docs/common_configurations.md
  docs/composable_services.md
  docs/contributing.md
  docs/deploying.md
  docs/design.md
  docs/diagrams/out/edpm.svg
  docs/diagrams/src/edpm.puml
  docs/inheritance.md
  docs/interacting_with_ansible.md
  docs/openstack_dataplane.md
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  docs/openstack_dataplaneservice.md
  mkdocs.yml
Labels: approved, lgtm

#268 Setting default go proxy for linter runs
  Makefile
Labels: approved, lgtm

#269 Upgrade mergo to v1.0.0 and change its url
  go.mod
  go.sum
  pkg/deployment/nova.go
Labels: approved, lgtm

#227 Remove ANSIBLE_VERBOSITY from samples
  config/samples/dataplane_v1beta1_openstackdataplane.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_ceph.yaml
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
Labels: approved, lgtm

#263 Resolve ansible hosts by hostname
  api/go.mod
  api/go.sum
  api/v1beta1/common.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/openstackdataplanerole_controller.go
  docs/openstack_dataplane.md
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  docs/openstack_dataplaneservice.md
  go.mod
  go.sum
  pkg/deployment/inventory.go
  pkg/deployment/ipam.go
  pkg/util/ansible_execution.go
Labels: approved, lgtm

#270 Don't keep CtlPlaneNetwork in pre-provisioned IPSet
  pkg/deployment/ipam.go
Labels: approved, lgtm

#271 Remove duplicated logic to set up webhook
  main.go
Labels: approved, lgtm

#272 [docs] Fix formatting for docs/deploying.md
  docs/deploying.md
Labels: approved, lgtm, ok-to-test

#267 Removing imports of tasks from main, as that is the default behavior
  config/services/dataplane_v1beta1_openstackdataplaneservice_configure_network.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_configure_os.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_install_os.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_validate_network.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/01-assert.yaml
Labels: approved, lgtm

#274 Wait for DNSMasq to be ready and reconcile for DNSMasq changes
  controllers/openstackdataplanerole_controller.go
  pkg/deployment/ipam.go
Labels: approved, lgtm

#279 Set mutated node dict in spec
  api/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  api/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  api/bases/dataplane.openstack.org_openstackdataplanes.yaml
  api/v1beta1/common.go
  api/v1beta1/openstackdataplane_webhook.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplanes.yaml
  docs/openstack_dataplane.md
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  docs/openstack_dataplaneservice.md
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml
Labels: approved, lgtm

#277 Remove redundant stuff from samples
  config/samples/dataplane_v1beta1_openstackdataplane.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal.yaml
Labels: approved, lgtm

#286 Add ability to override OpenStackDataPlane spec
  tests/functional/base_test.go
  tests/functional/openstackdataplane_controller_test.go
Labels: approved, lgtm

#282 Adds docs target to build documentation
  Makefile
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#289 Replace go test with Ginkgo
  Makefile
Labels: approved, lgtm

#288 Ensure InputReady condition for role/node
  api/v1beta1/conditions.go
  api/v1beta1/openstackdataplanenode_types.go
  api/v1beta1/openstackdataplanerole_types.go
  config/manifests/bases/dataplane-operator.clusterserviceversion.yaml
  config/samples/dataplane_v1beta1_openstackdataplane.yaml
  controllers/openstackdataplanenode_controller.go
  controllers/openstackdataplanerole_controller.go
  pkg/deployment/baremetal.go
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/01-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml
Labels: approved, lgtm

#292 Fix default route attribue in sample
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal_with_ipam.yaml
Labels: approved, lgtm

#299 configure internal dns in extracompute aee pods
  go.mod
  go.sum
  pkg/deployment/nova.go
Labels: approved, lgtm

#290 Remove DeleteNamespaces function
  tests/functional/base_test.go
Labels: approved, lgtm

#296 Use MatchingFields instead of MatchingLabels for listing nodes
  controllers/openstackdataplanenode_controller.go
  controllers/openstackdataplanerole_controller.go
Labels: approved, lgtm

#298 Populate node inventory from IPAM
  pkg/deployment/inventory.go
  pkg/deployment/ipam.go
Labels: approved, lgtm

#300 Ensure that all nodes are in SetupReady state before starting deploy
  api/v1beta1/openstackdataplanenode_types.go
  controllers/openstackdataplanerole_controller.go
Labels: approved, lgtm

#294 Only mark SetupCondition after resources created
  controllers/openstackdataplane_controller.go
Labels: approved, lgtm

#301 Configure renovate to pin k8s and controller-runtime for dev preview and pin ocp
  go.mod
  go.sum
  renovate.json
Labels: approved, lgtm

#283 Fix dataplane status when roles aren't found
  controllers/openstackdataplane_controller.go
  controllers/openstackdataplanerole_controller.go
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/00-dataplane-create.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml
Labels: approved, lgtm

#304 Remove usage of NAD ready condition
  controllers/openstackdataplanenode_controller.go
  controllers/openstackdataplanerole_controller.go
Labels: approved, lgtm

#307 Update to use shared renovate config
  renovate.json
Labels: approved

#281 CSV: Set operator-type: non-standalone
  config/manifests/bases/dataplane-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#313 Avoid bumping our own api package version
  renovate.json
Labels: approved, lgtm

#315 Add $SKIP_FIREWALL
  hack/configure_local_webhook.sh
Labels: approved, lgtm

#316 Don't drop ctlplane network for pre-provisioned
  pkg/deployment/ipam.go
Labels: approved, lgtm

#317 Set conditions for BM provsioning, ipam and dns
  controllers/openstackdataplanerole_controller.go
  pkg/deployment/baremetal.go
  pkg/deployment/ipam.go
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/01-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml
Labels: approved, lgtm

#319 Use json.RawMessage for AnsibleVars
  api/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  api/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  api/bases/dataplane.openstack.org_openstackdataplanes.yaml
  api/v1beta1/common.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplanes.yaml
  config/samples/dataplane_v1beta1_openstackdataplane.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal_with_ipam.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_ceph.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_customnetworks.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenode_edpm_compute_0.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenode_edpm_compute_0_full.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenode_edpm_compute_1.yaml
  config/samples/dataplane_v1beta1_openstackdataplanerole_edpm_compute.yaml
  docs/deploying.md
  docs/inheritance.md
  docs/openstack_dataplane.md
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  docs/openstack_dataplaneservice.md
  pkg/deployment/inventory.go
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
Labels: approved, lgtm
