Repository openstack-k8s-operators/dataplane-operator, pull requests merged in 2023-06, with the labels that each got.

#216 OpenStackDataPlane sample CR for Nova Ceph Config
  config/samples/dataplane_v1beta1_openstackdataplane_ceph.yaml
Labels: approved, lgtm

#210 Move OpenStackAnsibleEEImage field to OpenStackDataPlaneService
  api/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  api/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  api/bases/dataplane.openstack.org_openstackdataplanes.yaml
  api/bases/dataplane.openstack.org_openstackdataplaneservices.yaml
  api/v1beta1/common.go
  api/v1beta1/openstackdataplanenode_types.go
  api/v1beta1/openstackdataplanerole_types.go
  api/v1beta1/openstackdataplaneservice_types.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplanes.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplaneservices.yaml
  controllers/openstackdataplane_controller.go
  controllers/openstackdataplanenode_controller.go
  controllers/openstackdataplanerole_controller.go
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  pkg/deployment/deployment.go
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/00-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-dataplane-create.yaml
Labels: approved, lgtm

#208 Add edpm baremetal CI job
  zuul.d/jobs.yaml
  zuul.d/projects.yaml
Labels: approved, lgtm

#205 Make dataplanenode controller watch dataplanerole
  controllers/openstackdataplanenode_controller.go
  controllers/openstackdataplanerole_controller.go
Labels: approved, lgtm

#221 Add sample for baremetal deployment
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal.yaml
Labels: approved, lgtm

#223 Revert "Move services under NodeSection."
  api/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  api/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  api/bases/dataplane.openstack.org_openstackdataplanes.yaml
  api/v1beta1/common.go
  api/v1beta1/openstackdataplanenode_types.go
  api/v1beta1/openstackdataplanerole_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplanes.yaml
  config/samples/dataplane_v1beta1_openstackdataplane.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_ceph.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenode.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenode_edpm_compute_0.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenode_edpm_compute_0_full.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenode_edpm_compute_1.yaml
  config/samples/dataplane_v1beta1_openstackdataplanerole.yaml
  config/samples/dataplane_v1beta1_openstackdataplanerole_edpm_compute.yaml
  controllers/openstackdataplane_controller.go
  controllers/openstackdataplanenode_controller.go
  controllers/openstackdataplanerole_controller.go
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  tests/functional/base_test.go
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/00-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-dataplane-create.yaml
Labels: approved, lgtm

#224 Use NewOpenStackAnsibleEE
  api/bases/dataplane.openstack.org_openstackdataplaneservices.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/openstackdataplaneservice_types.go
  config/crd/bases/dataplane.openstack.org_openstackdataplaneservices.yaml
  go.mod
  go.sum
  pkg/util/ansible_execution.go
Labels: approved, lgtm

#234 Document bootstrap command for system registration
  .pre-commit-config.yaml
  docs/common_configurations.md
  docs/composable_services.md
  docs/deploying.md
  mkdocs.yml
Labels: approved

#236 Create services as part of Role reconcile
  Dockerfile
  api/go.mod
  api/go.sum
  config/rbac/role.yaml
  controllers/openstackdataplanerole_controller.go
  docs/composable_services.md
  docs/deploying.md
  go.mod
  go.sum
Labels: approved, lgtm

#238 Document link changes
  README.md
Labels: approved, lgtm, ok-to-test

#233 Fix edpm_ovn related variable names in example CRs
  config/samples/dataplane_v1beta1_openstackdataplane.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_ceph.yaml
  config/samples/dataplane_v1beta1_openstackdataplane_customnetworks.yaml
  tests/kuttl/tests/dataplane-create-test/00-assert.yaml
Labels: approved, lgtm

#240 Raise kuttl test timeout to 10m
  kuttl-test.yaml
Labels: approved, lgtm

#239 Add docs for network isolation
  docs/common_configurations.md
  docs/composable_services.md
Labels: approved, lgtm

#241 Add irrelevant-files list in zuul-jobs
  zuul.d/jobs.yaml
Labels: approved, lgtm

#244 Bump controller manager memory request and limit
  config/manager/manager.yaml
Labels: approved, lgtm

#246 Cleanup configmaps after node/role cleanup
  pkg/deployment/inventory.go
Labels: approved, lgtm

#245 Document AEE label
  docs/interacting_with_ansible.md
Labels: approved, lgtm

#249 Use IPAM in baremetal sample
  config/samples/dataplane_v1beta1_openstackdataplane_baremetal_with_ipam.yaml
Labels: approved, lgtm

#232 Remove default OpenStackAnsibleEERunnerImage
  api/v1beta1/common.go
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  docs/openstack_dataplaneservice.md
  pkg/util/ansible_execution.go
Labels: approved, lgtm

#252 Make AnsibleSSHPrivateKeySecret validation Optional
  api/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  api/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  api/bases/dataplane.openstack.org_openstackdataplanes.yaml
  api/v1beta1/common.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodes.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplaneroles.yaml
  config/crd/bases/dataplane.openstack.org_openstackdataplanes.yaml
  docs/openstack_dataplanenode.md
  docs/openstack_dataplanerole.md
  docs/openstack_dataplaneservice.md
Labels: approved, lgtm

#253 Remove openstack from workflow name
  .github/workflows/build-dataplane-operator.yaml
  .github/workflows/release-dataplane-operator.yaml
Labels: approved, lgtm

#254 Use HostName in BaremetalSet Spec
  pkg/deployment/baremetal.go
  pkg/deployment/inventory.go
  pkg/deployment/ipam.go
Labels: approved, lgtm
