Repository openstack-k8s-operators/dataplane-operator, pull requests merged in 2024-02, with the labels that each got.

#637 Add docs for BM provisioning and scaling
  docs/deploying.md
  docs/deploying_baremetal.md
  docs/scaling.md
  mkdocs.yml
Labels: approved, lgtm

#632 Convert docs from MarkDown to AsciiDoc
  .github/workflows/docs.yaml
  .gitignore
  Gemfile
  Makefile
  docs/Makefile
  docs/architecture.md
  docs/assemblies/common_configurations.adoc
  docs/assemblies/composable_services.adoc
  docs/assemblies/contributing.adoc
  docs/assemblies/custom_resources.adoc
  docs/assemblies/deploying.adoc
  docs/assemblies/deploying_baremetal.adoc
  docs/assemblies/design.adoc
  docs/assemblies/index.adoc
  docs/assemblies/inheritance.adoc
  docs/assemblies/interacting_with_ansible.adoc
  docs/assemblies/scaling.adoc
  docs/assemblies/tls.adoc
  docs/contributing.md
  docs/diagrams/out/edpm.svg
  docs/diagrams/src/edpm.puml
  docs/doc_requirements.txt
  docs/images/.gitkeep
  docs/images/openstack-logo.png
  docs/index.md
  docs/main.adoc
  docs/openstack_dataplanedeployment.md
  docs/openstack_dataplanenodeset.md
  docs/openstack_dataplaneservice.md
  mkdocs.yml
  zuul.d/jobs.yaml
Labels: approved, lgtm

#640 Replace ctlplane_subnet_cidr in nic config samples
  config/samples/nic-config-samples/bonds_vlans/bonds_vlans.j2
  config/samples/nic-config-samples/bonds_vlans/bonds_vlans_dpdk.j2
  config/samples/nic-config-samples/bonds_vlans/bonds_vlans_storage.j2
  config/samples/nic-config-samples/bonds_vlans/controller_no_external.j2
  config/samples/nic-config-samples/multiple_nics/multiple_nics.j2
  config/samples/nic-config-samples/multiple_nics/multiple_nics_dpdk.j2
  config/samples/nic-config-samples/multiple_nics/multiple_nics_dvr.j2
  config/samples/nic-config-samples/multiple_nics_vlans/multiple_nics_vlans.j2
  config/samples/nic-config-samples/multiple_nics_vlans/multiple_nics_vlans_dpdk.j2
  config/samples/nic-config-samples/multiple_nics_vlans/multiple_nics_vlans_dvr.j2
  config/samples/nic-config-samples/single_nic_vlans/controller_no_external.j2
  config/samples/nic-config-samples/single_nic_vlans/single_nic_vlans.j2
  config/samples/nic-config-samples/single_nic_vlans/single_nic_vlans_bgp.j2
  config/samples/nic-config-samples/single_nic_vlans/single_nic_vlans_bgp_ovn.j2
  config/samples/nic-config-samples/single_nic_vlans/single_nic_vlans_storage.j2
Labels: approved, lgtm

#643 Remove debug from aee
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/01-assert.yaml
  tests/kuttl/tests/dataplane-deploy-no-nodes-test/02-assert.yaml
  tests/kuttl/tests/dataplane-service-config/00-assert.yaml
Labels: approved, lgtm

#633 This change ensures the `dataplane-operator` is built with FIPS compliance
  .prow_ci.env
  Dockerfile
  Makefile
Labels: approved, lgtm

#629 No dup nodes
  api/go.mod
  api/v1beta1/openstackdataplanenodeset_webhook.go
  tests/functional/openstackdataplanenodeset_webhook_test.go
Labels: approved, lgtm

#615 DDP package selection service
  config/services/dataplane_v1beta1_openstackdataplaneservice_ddp_package_option.yaml
Labels: approved, lgtm

#645 confgure-ovs-dpk service document changes
  docs/assemblies/composable_services.adoc
Labels: approved, lgtm

#639 Add kuttl tests to test with IPAM
  kuttl-test.yaml
  pkg/deployment/ipam.go
  tests/kuttl/tests/dataplane-with-ipam-create-test/00-assert.yaml
  tests/kuttl/tests/dataplane-with-ipam-create-test/00-dataplane-create.yaml
Labels: approved, lgtm

#644 For baremetal nodes use CloudUserName as AnsibleUser
  api/v1beta1/openstackdataplanenodeset_webhook.go
Labels: approved, lgtm

#536 OvS DPDK dataplane deployment and nodeset sample CR files
  config/samples/dataplane_v1beta1_openstackdataplanedeployment_ovs_dpdk.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
Labels: approved, lgtm

#491 Generate config hash for nodeTemplate and nodes sections
  api/bases/dataplane.openstack.org_openstackdataplanenodesets.yaml
  api/v1beta1/openstackdataplanenodeset_types.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodesets.yaml
  controllers/openstackdataplanenodeset_controller.go
  docs/assemblies/custom_resources.adoc
  docs/assemblies/deploying.adoc
  tests/functional/openstackdataplanenodeset_controller_test.go
Labels: approved, lgtm

#647 Add more status fields to ipm kuttl test
  api/bases/dataplane.openstack.org_openstackdataplanenodesets.yaml
  api/v1beta1/openstackdataplanenodeset_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodesets.yaml
  controllers/openstackdataplanenodeset_controller.go
  tests/kuttl/tests/dataplane-with-ipam-create-test/00-assert.yaml
Labels: approved, lgtm

#649 Run make docs on API changes
  .github/workflows/docs.yaml
  docs/assemblies/custom_resources.adoc
Labels: approved, lgtm

#654 Re-word PreProvisioned description
  api/v1beta1/openstackdataplanenodeset_types.go
  docs/assemblies/custom_resources.adoc
Labels: approved, lgtm

#642 Add Swift service and nodeset sample
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_swift.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_swift.yaml
Labels: approved, lgtm

#653 Adding enable chassis gateway config
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
Labels: approved, lgtm

#652 Fix BaremetalSetTemplate spelling
  controllers/openstackdataplanenodeset_controller.go
Labels: approved, lgtm

#660 Remove extra "_" at BGP sample templates
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_bgp.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_bgp_ovn_cluster.yaml
Labels: approved, lgtm

#659 Removed KubeService from API as it does not get created anymore
  api/v1beta1/openstackdataplaneservice_types.go
  api/v1beta1/zz_generated.deepcopy.go
  docs/assemblies/custom_resources.adoc
Labels: approved, lgtm

#655 Add make docs to pre-commit
  .pre-commit-config.yaml
Labels: approved, lgtm

#648 Improve user docs
  docs/assemblies/common_configurations.adoc
  docs/assemblies/composable_services.adoc
  docs/assemblies/con_data-plane-services.adoc
  docs/assemblies/con_provisioning-bare-metal-data-plane-nodes.adoc
  docs/assemblies/creating-the-data-plane.adoc
  docs/assemblies/deploying.adoc
  docs/assemblies/index.adoc
  docs/assemblies/inheritance.adoc
  docs/assemblies/interacting_with_ansible.adoc
  docs/assemblies/proc_building-a-custom-ansible-runner-image.adoc
  docs/assemblies/proc_configuring-a-node-set-for-a-Compute-feature-or-workload.adoc
  docs/assemblies/proc_creating-a-custom-service.adoc
  docs/assemblies/proc_creating-a-set-of-data-plane-nodes.adoc
  docs/assemblies/proc_creating-the-SSH-key-secrets.adoc
  docs/assemblies/proc_deploying-the-data-plane.adoc
  docs/assemblies/proc_troubleshooting-data-plane-creation-and-deployment.adoc
  docs/assemblies/ref_OpenStackDataPlaneNodeSet-CR-properties.adoc
  docs/assemblies/ref_data-plane-conditions-and-states.adoc
  docs/assemblies/ref_example-OpenStackDataPlaneNodeSet-CR-for-bare-metal-nodes.adoc
  docs/assemblies/ref_example-OpenStackDataPlaneNodeSet-CR-for-preprovisioned-nodes.adoc
  docs/assemblies/scaling.adoc
  docs/main.adoc
Labels: approved, lgtm

#663 Rename reconcileFunction to dnsMasqWatcher
  controllers/openstackdataplanenodeset_controller.go
Labels: approved, lgtm

#658 Default OVN chassis gw should be false for compute nodes.
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
Labels: approved, lgtm

#488 structured logging2
  controllers/openstackdataplanedeployment_controller.go
  controllers/openstackdataplanenodeset_controller.go
  main.go
  tests/functional/suite_test.go
Labels: approved, lgtm, ok-to-test

#664 Drop warning about existing netconfig during kuttl
  Makefile
Labels: approved, lgtm

#651 Add kuttl tests for TLS certs
  config/rbac/role.yaml
  controllers/openstackdataplanedeployment_controller.go
  tests/kuttl/tests/dataplane-deploy-tls-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/00-dataplane-create.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/01-create-cert-issuers.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/02-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/02-dataplane-deploy.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/03-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/03-dataplane-deploy-services-override.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/certs.yaml
Labels: approved, lgtm

#621 All sample files can use IPAM
  config/samples/dataplane_v1beta1_openstackdataplanenodeset.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_baremetal_with_ipam.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_bgp.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_bgp_ovn_cluster.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ceph.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_customnetworks.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_networker.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_nmstate.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_sriov.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_with_ipam.yaml
Labels: approved, lgtm

#662 Easier way to get a test coverage report
  Makefile
Labels: approved, lgtm

#673 Unique LeaderElectionID
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  main.go
Labels: approved

#666 Update status on setup errors
  controllers/openstackdataplanedeployment_controller.go
  controllers/openstackdataplanenodeset_controller.go
  pkg/deployment/deployment.go
Labels: approved, lgtm

#674 Cleanup golangci-lint
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  .pre-commit-config.yaml
Labels: approved, lgtm

#671 Cleanup ovs_dpdk sample
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
Labels: approved, lgtm

#670 Getting network name missing in dictionary issue
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
Labels: approved, lgtm

#668 Bumping actions to use node.js-20
  .github/workflows/codeql.yml
  .github/workflows/docs.yaml
  .github/workflows/release-dataplane-operator.yaml
Labels: approved, lgtm

#678 Fix ansible var nit
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
Labels: approved, lgtm

#677 Ensure we match case insensitive cert networks
  config/services/dataplane_v1beta1_openstackdataplaneservice_libvirt.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_nova.yaml
  pkg/deployment/cert.go
  pkg/deployment/ipam.go
Labels: approved, lgtm

#679 [renovate]Remove golang constraint
  renovate.json
Labels: approved, lgtm

#669 Updating the dataplane docs
  OWNERS_ALIASES
  docs/OWNERS
  docs/assemblies/ansible.adoc
  docs/assemblies/common_configurations.adoc
  docs/assemblies/con_data-plane-services.adoc
  docs/assemblies/condition.adoc
  docs/assemblies/creating-the-data-plane.adoc
  docs/assemblies/hashes.adoc
  docs/assemblies/index.adoc
  docs/assemblies/interacting_with_ansible.adoc
  docs/assemblies/ipam.adoc
  docs/assemblies/proc_creating-a-custom-service.adoc
  docs/assemblies/ref_OpenStackDataPlaneNodeSet-CR-properties.adoc
  docs/assemblies/tls.adoc
  docs/main.adoc
Labels: approved, lgtm

#675 Sync EnvTest version with k8s version
  Makefile
Labels: approved, lgtm

#626 Drop OpenStackDataPlaneService.Spec.Label field
  api/bases/dataplane.openstack.org_openstackdataplaneservices.yaml
  api/v1beta1/openstackdataplaneservice_types.go
  config/crd/bases/dataplane.openstack.org_openstackdataplaneservices.yaml
  docs/assemblies/custom_resources.adoc
  pkg/deployment/deployment.go
  pkg/util/ansible_execution.go
  pkg/util/const.go
  tests/functional/openstackdataplanedeployment_controller_test.go
  tests/kuttl/tests/dataplane-deploy-tls-test/00-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/00-dataplane-create.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/03-dataplane-deploy-services-override.yaml
  tests/kuttl/tests/dataplane-service-config/00-create.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml
  tests/kuttl/tests/dataplane-service-custom-image/00-dataplane-create.yaml
Labels: approved, lgtm

#636 Documentation pod status reporting
  controllers/openstackdataplanenodeset_controller.go
  docs/assemblies/proc_troubleshooting-data-plane-creation-and-deployment.adoc
Labels: approved, lgtm

#676 Pass instanceSpec.CtlPlaneIP in CIDR notation
  pkg/deployment/baremetal.go
  tests/functional/openstackdataplanenodeset_webhook_test.go
Labels: approved, lgtm

#686 Hash the entire NodeSet spec
  controllers/openstackdataplanenodeset_controller.go
Labels: approved, lgtm

#689 Regenerate go.mod indirect dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#695 Update status on setup/input errors
  controllers/openstackdataplanedeployment_controller.go
  controllers/openstackdataplanenodeset_controller.go
Labels: approved, lgtm

#700 Fix README links
  README.md
Labels: approved, lgtm

#697 Temporarily fix issuers
  config/services/dataplane_v1beta1_openstackdataplaneservice_libvirt.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_nova.yaml
  pkg/deployment/cert.go
  tests/kuttl/tests/dataplane-deploy-tls-test/02-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/03-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/03-dataplane-deploy-services-override.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/certs.yaml
Labels: approved, lgtm

#703 Remove markdown leftovers
  docs/openstack_dataplanedeployment.md
  docs/openstack_dataplanenodeset.md
  docs/openstack_dataplaneservice.md
Labels: approved, lgtm

#691 Test expansion
  tests/functional/base_test.go
  tests/functional/openstackdataplanedeployment_controller_test.go
  tests/functional/openstackdataplanenodeset_controller_test.go
  tests/functional/openstackdataplanenodeset_webhook_test.go
Labels: approved, lgtm

#705 Split user and dev docs
  .github/workflows/docs.yaml
  README.md
  docs/Makefile
  docs/dev.adoc
  docs/index.html
  docs/user.adoc
Labels: approved, lgtm

#702 Add service certs to secret hash
  controllers/openstackdataplanedeployment_controller.go
  docs/assemblies/tls.adoc
  pkg/deployment/cert.go
  pkg/deployment/const.go
  pkg/deployment/hashes.go
  tests/kuttl/tests/dataplane-deploy-tls-test/02-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/03-assert.yaml
Labels: approved, lgtm

#708 OVS DPDK & SRIOV dataplane service order changes
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_sriov.yaml
Labels: approved, lgtm

#710 Added the defaults for Telemetry compute images
  api/v1beta1/openstackdataplanenodeset_types.go
  controllers/openstackdataplanenodeset_controller.go
  docs/assemblies/custom_resources.adoc
  pkg/deployment/inventory.go
Labels: approved, lgtm

#713 Drop service label field from config/services resources
  config/services/dataplane_v1beta1_openstackdataplaneservice_bootstrap.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_client.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_configure_network.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_configure_os.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_configure_ovs_dpdk.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_ddp_package_option.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_download_cache.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_frr.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_install_certs.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_install_os.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_libvirt.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_logging.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_neutron_dhcp.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_neutron_metadata.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_neutron_ovn.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_neutron_sriov.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_nova.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_os_reboot.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_ovn.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_ovn_bgp_agent.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_run_os.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_swift.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_telemetry.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_validate_network.yaml
Labels: approved, lgtm

#711 remove libvirt image defaulting
  api/v1beta1/openstackdataplanenodeset_types.go
  controllers/openstackdataplanenodeset_controller.go
  docs/assemblies/custom_resources.adoc
  pkg/deployment/inventory.go
  tests/functional/base_test.go
  tests/functional/openstackdataplanenodeset_controller_test.go
Labels: approved, lgtm

#712 Add ssh-known-hosts service
  api/bases/dataplane.openstack.org_openstackdataplanenodesets.yaml
  api/v1beta1/openstackdataplanenodeset_types.go
  config/crd/bases/dataplane.openstack.org_openstackdataplanenodesets.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_ssh_known_hosts.yaml
  tests/functional/openstackdataplanenodeset_controller_test.go
Labels: approved, lgtm

#716 Added CeilometerIpmi image to defaults
  api/v1beta1/openstackdataplanenodeset_types.go
  controllers/openstackdataplanenodeset_controller.go
  docs/assemblies/custom_resources.adoc
  pkg/deployment/inventory.go
Labels: approved, lgtm

#709 Refer to issuers by label instead of name
  api/v1beta1/openstackdataplaneservice_types.go
  config/manifests/bases/dataplane-operator.clusterserviceversion.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_libvirt.yaml
  config/services/dataplane_v1beta1_openstackdataplaneservice_nova.yaml
  docs/assemblies/custom_resources.adoc
  docs/assemblies/tls.adoc
  pkg/deployment/cert.go
  tests/kuttl/tests/dataplane-deploy-tls-test/03-dataplane-deploy-services-override.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/certs.yaml
Labels: approved, lgtm

#714 Fix cert secret names
  pkg/deployment/cert.go
  tests/kuttl/tests/dataplane-deploy-tls-test/01-create-cert-issuers.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/02-assert.yaml
  tests/kuttl/tests/dataplane-deploy-tls-test/03-assert.yaml
Labels: approved, lgtm

#720 Update Swift sample
  config/samples/dataplane_v1beta1_openstackdataplanenodeset_swift.yaml
Labels: approved, lgtm

#672 Instruct install_certs to generate certificates for Telemetry agents
  config/services/dataplane_v1beta1_openstackdataplaneservice_telemetry.yaml
Labels: approved, lgtm
